### ISSUE TITLE
Footer in homepage is duplicated

### ISSUE THREAD

**Issue by AlberTajuelo** [FragmentX/FRAGMENTX#63]
It should be enough to remove it in index page:
https://github.com/FragmentX/FRAGMENTX/blob/master/app/views/home/index.html.erb#L60-L65

https://github.com/FragmentX/FRAGMENTX/blob/master/app/views/layouts/application.html.erb#L52-L57

![image](https://user-images.githubusercontent.com/1073373/48932796-fdfaaa80-eefd-11e8-867b-2319f75095c5.png)

**Comment by alvarocasadoc** [comment]
Hey, @AlberTajuelo! Thanks for pointing at this issue. Just fixed it and got a new version up and rolling 👍
